// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLpTk7V0PMbq4rQmC2w9tF9QdOhpPhUo',
    appId: '1:130022592189:web:7a645e6d4045f41415f1d4',
    messagingSenderId: '130022592189',
    projectId: 'flastchat-b24a5',
    authDomain: 'flastchat-b24a5.firebaseapp.com',
    storageBucket: 'flastchat-b24a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0n1kvcmSbqvGVjSJsQSroaBm_-dBdBPs',
    appId: '1:130022592189:ios:18ed5cd159d07bf815f1d4',
    messagingSenderId: '130022592189',
    projectId: 'flastchat-b24a5',
    storageBucket: 'flastchat-b24a5.appspot.com',
    iosClientId: '130022592189-73grto7nupgssjv6lv7034tl6vb3babb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0n1kvcmSbqvGVjSJsQSroaBm_-dBdBPs',
    appId: '1:130022592189:ios:18ed5cd159d07bf815f1d4',
    messagingSenderId: '130022592189',
    projectId: 'flastchat-b24a5',
    storageBucket: 'flastchat-b24a5.appspot.com',
    iosClientId: '130022592189-73grto7nupgssjv6lv7034tl6vb3babb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatproject',
  );
}
